### ISSUE TITLE
[BUG] Exact type of handled event is lost

### ISSUE THREAD

**Issue by pshurygin** [TinkoffCreditSystems/ng-event-plugins#7] opened 2020-11-26 14:17 UTC
# 🐞 Bug report

### Description

Exact type of the $event variable is lost when using `.stop` and `.prevent`. This leads to compilation errors like this:

`Argument of type 'Event' is not assignable to parameter of type 'MouseEvent'.`

### Reproduction

https://stackblitz.com/edit/angular-ivy-nmv1wb

### Expected behaviour

The type of $event should be preserved

### Versions

See stackblitz

**Comment by waterplea** [comment] 2020-11-26 15:36
Hi. Thanks for bringing this up. I will close this issue in favor of another one you raised, because the root cause it probably the same:
https://github.com/TinkoffCreditSystems/ng-event-plugins/issues/8

**Closed by waterplea** 2020-11-26 15:36 UTC
